version: '3.8'
services:

  postgres:
    image: postgres:14
    networks:
      - watr-net 
    container_name: postgres 
    volumes:
      - postgres-data:/var/lib/postgres/data
      - ${CONFIG}/docker-entrypoint-initdb:/docker-entrypoint-initdb.d
    restart: always
    ports:
       - "5432:5432"
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 

  adminer:
    image: adminer
    networks:
      - watr-net 
    restart: always
    ports:
      - 8080:8080
